# Generated by Django 5.1.2 on 2024-11-03 04:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('full_name', models.CharField(max_length=150, verbose_name='full_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is super user')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
